name: CI/CD Flask App (with tar)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r CI-CD/requirements.txt

      - name: Run tests
        run: pytest CI-CD/test_app1.py -v


  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact with tar
        run: |
          tar -czf flask-app.tar.gz CI-CD/*.py CI-CD/requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact-flask
          path: flask-app.tar.gz


  deploy-dev:
    runs-on: ubuntu-latest
    needs: package
    environment: dev

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact-flask

      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV"
          mkdir dev-release
          tar -xzf flask-app.tar.gz -C dev-release
          ls dev-release


  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact-flask

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD"
          mkdir prod-release
          tar -xzf flask-app.tar.gz -C prod-release
          ls prod-release






# name: CI Advanced Python Tests

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run tests
#         run: python -m pytest





# deploy-dev:
#   Runs-on: ubuntu-lastest
#   needs:package
#   environment:dev
#   steps:
#   -uses:action/download-artifact@v4
#   with:
#     name:app-artiact-flask
#     -name: Deploy to dev
#     run:
#     echo "Deploying to DEV"
#     mkdir dev-release
#     tar -xzf flask-app.at.gz -C dev-released


# deploy-prod:
#   Runs-on: ubuntu-lastest
#   needs:deploy-dev
#   environment: prod
#   steps:
#    - uses: actions/download-artifact@v4
#      with:
#       name: app-artifact-flask

#     -name: Deploy to prod
#       run: |
#       echo "Deploying to PROD"
#       mkdir prod-release
#       tar -xzf flask-app.